### ISSUE TITLE
Library version is not working

### ISSUE THREAD

**Issue by rublin** [arduino/compile-sketches#200]
### Describe the problem

For [my project](https://github.com/rublin/russian-losses-watch), I need to use libraries with specific versions (not the recent ones). So, I prepared the workflow with a list of libraries (even with dependencies):
```yaml
          libraries: |
            - name: WiFiManager
              version: 2.0.16-rc.2
            - name: ArduinoJson
              version: 6.21.3
            - name: ESPDateTime
              version: 1.0.4
            - name: SD
              version: 1.2.4
            - name: Adafruit seesaw Library
              version: 1.7.3
            - name: Adafruit BusIO
              version: 1.14.4
            - name: Adafruit GFX Library
              version: 1.11.7
            - name: Adafruit ST7735 and ST7789 Library
              version: 1.10.3
            - name: U8g2_for_Adafruit_GFX
              version: 1.8.0
            - name: DoubleResetDetector
              version: 1.0.3
```

But for some reason I see this **replacing** in logs:
`Replacing Adafruit GFX Library@1.11.7 with Adafruit GFX Library@1.11.9...`
`Replacing Adafruit seesaw Library@1.7.3 with Adafruit seesaw Library@1.7.4...`
```
Running command: /home/runner/bin/arduino-cli lib install Adafruit ST7735 and ST7789 Library@1.10.3 --log-level warn --verbose 
   Already installed Adafruit BusIO@1.14.5
  Already installed Adafruit ST7735 and ST7789 Library@1.10.3
  Already installed SD@1.2.4
  Downloading Adafruit GFX Library@1.11.9...
  Adafruit GFX Library@1.11.9 Adafruit GFX Library@1.11.9 already downloaded
  Installing Adafruit GFX Library@1.11.9...
  Replacing Adafruit GFX Library@1.11.7 with Adafruit GFX Library@1.11.9...
  Installed Adafruit GFX Library@1.11.9
  Downloading Adafruit seesaw Library@1.7.4...
  
  Adafruit seesaw Library@1.7.4 0 B / 122.88 KiB    0.00%
  Adafruit seesaw Library@1.7.4 downloaded
  Installing Adafruit seesaw Library@1.7.4...
  Replacing Adafruit seesaw Library@1.7.3 with Adafruit seesaw Library@1.7.4...
  Installed Adafruit seesaw Library@1.7.4
```
Maybe it's my mistake in configuration, but I don't know how to force using the specific versions. 

Any ideas?

### To reproduce

Try to use a specific version of a dependency. In my case, **Adafruit GFX Library@1.11.7** for **Adafruit ST7735 and ST7789 Library@1.10.3**

### Expected behavior

Compiling the project with specific versions of the libraries.

### 'arduino/compile-sketches' version

1.1.0

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/compile-sketches/issues?q=)
- [X] I verified the problem still occurs when using the latest version
- [X] My report contains all necessary details
