### ISSUE TITLE
Incorrect and insufficient documentation of `cli-compile-args` input data format

### ISSUE THREAD

**Issue by Jackbennett** [arduino/compile-sketches#207]
### Describe the problem

* It's not clear to me why https://github.com/arduino/compile-sketches#cli-compile-flags has an issue with the attached config;
* Should I expect this matrix argument to work with this double-yaml parsing going on?

config;
```yaml
name: Compile Sketch

# The workflow will run on every push and pull request to the repository
on:
  push:
    paths:
      - '.github/workflows/sketches.yaml'
      - '*.ino'
      - '*.cpp'
      - '*.h'
  pull_request:
    paths:
      - '.github/workflows/sketches.yaml'
      - '*.ino'
      - '*.cpp'
      - '*.h'

jobs:
  compile-sketch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # variants listed in Defines.h:11
        variant: [ 0, 1 , 2, 3 ]

    steps:
      # This step makes the contents of the repository available to the workflow
      - name: Checkout repository
        uses: actions/checkout@v2

      # For more information: https://github.com/arduino/compile-sketches#readme
      - name: Compile sketch
        uses: arduino/compile-sketches@v1
        with:
          # The default is to compile for the Arduino Uno board. If you want to compile for other boards, use the `fqbn` input.
          fqbn: arduino:avr:mega
          sketch-paths: |
            # Configure the action to search all folders under the root of the repository for sketches and compile them.
            # This is formatted as a YAML list, which makes it possible to have multiple sketch paths if needed.
            - ./main.ino
          cli-compile-flags: |
            - --build-property build.extra_flags=-VARIANT_SELECTED=${{ matrix.variant }}
```

### To reproduce

```
# Run action
  poetry run \
    python compilesketches/compilesketches.py
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.11.2/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.11.2/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.2/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.2/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.2/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.11.2/x64/lib
    INPUT_CLI-VERSION: latest
    INPUT_FQBN: arduino:avr:mega
    INPUT_LIBRARIES: - source-path: ./
    INPUT_PLATFORMS: 
    INPUT_SKETCH-PATHS: # Configure the action to search all folders under the root of the repository for sketches and compile them.
  # This is formatted as a YAML list, which makes it possible to have multiple sketch paths if needed.
  - ./main.ino
  
    INPUT_CLI-COMPILE-FLAGS: - --build-property build.extra_flags=-VARIANT_SELECTED=0
    INPUT_VERBOSE: false
    INPUT_GITHUB-TOKEN: 
    INPUT_ENABLE-DELTAS-REPORT: false
    INPUT_ENABLE-WARNINGS-REPORT: false
    INPUT_SKETCHES-REPORT-PATH: sketches-reports
Compiling sketch: .
  Error: unknown flag: --build-property build.extra_flags
  Usage:
    arduino-cli compile [flags]
  
  Examples:
    /home/runner/bin/arduino-cli compile -b arduino:avr:uno /home/user/Arduino/MySketch
    /home/runner/bin/arduino-cli compile -b arduino:avr:uno --build-property "build.extra_flags=\"-DMY_DEFINE=\"hello world\"\"" /home/user/Arduino/MySketch
    /home/runner/bin/arduino-cli compile -b arduino:avr:uno --build-property "build.extra_flags=-DPIN=2 \"-DMY_DEFINE=\"hello world\"\"" /home/user/Arduino/MySketch
    /home/runner/bin/arduino-cli compile -b arduino:avr:uno --build-property build.extra_flags=-DPIN=2 --build-property "compiler.cpp.extra_flags=\"-DSSID=\"hello world\"\"" /home/user/Arduino/MySketch
  
  
  Flags:
        --board-options strings                 List of board options separated by commas. Or can be used multiple times for multiple options.
        --build-cache-path string               Builds of 'core.a' are saved into this path to be cached and reused.
        --build-path string                     Path where to save compiled files. If omitted, a directory will be created in the default temporary path of your OS.
        --build-property stringArray            Override a build property with a custom value. Can be used multiple times for multiple properties.
        --clean                                 Optional, cleanup the build folder and do not use any cached build.
        --discovery-timeout duration            Max time to wait for port discovery, e.g.: 30s, 1m (default 1s)
        --dump-profile                          Create and print a profile configuration from the build.
        --encrypt-key string                    The name of the custom encryption key to use to encrypt a binary during the compile process. Used only by the platforms that support it.
    -e, --export-binaries                       If set built binaries will be exported to the sketch folder.
    -b, --fqbn string                           Fully Qualified Board Name, e.g.: arduino:avr:uno
    -h, --help                                  help for compile
        --keys-keychain string                  The path of the dir to search for the custom keys to sign and encrypt a binary. Used only by the platforms that support it.
        --libraries strings                     Path to a collection of libraries. Can be used multiple times or entries can be comma separated.
        --library strings                       Path to a single library’s root folder. Can be used multiple times or entries can be comma separated.
        --only-compilation-database             Just produce the compilation database, without actually compiling. All build commands are skipped except pre* hooks.
        --optimize-for-debug                    Optional, optimize compile output for debugging, rather than for release.
        --output-dir string                     Save build artifacts in this directory.
    -p, --port string                           Upload port address, e.g.: COM3 or /dev/ttyACM2
        --preprocess                            Print preprocessed code to stdout instead of compiling.
    -m, --profile string                        Sketch profile to use
    -P, --programmer string                     Programmer to use, e.g: atmel_ice
    -l, --protocol string                       Upload port protocol, e.g: serial
        --quiet                                 Optional, suppresses almost every output.
        --show-properties string[="expanded"]   Show build properties. The properties are expanded, use "--show-properties=unexpanded" if you want them exactly as they are defined. (default "disabled")
        --sign-key string                       The name of the custom signing key to use to sign a binary during the compile process. Used only by the platforms that support it.
    -u, --upload                                Upload the binary after the compilation.
    -t, --verify                                Verify uploaded binary after the upload.
        --warnings string                       Optional, can be: none, default, more, all. Used to tell gcc which warning level to use (-W flag). (default "none")
  
  Global Flags:
        --additional-urls strings   Comma-separated list of additional URLs for the Boards Manager.
        --config-file string        The custom config file (if not specified the default will be used).
        --format string             The output format for the logs, can be: text, json, jsonmini, yaml (default "text")
        --log                       Print the logs on the standard output.
        --log-file string           Path to the file where logs will be written.
        --log-format string         The output format for the logs, can be: text, json
        --log-level string          Messages with this level and above will be logged. Valid levels are: trace, debug, info, warn, error, fatal, panic
        --no-color                  Disable colored output.
  
  unknown flag: --build-property build.extra_flags
  
Error: Compilation failed
Error: One or more compilations failed
Error: Process completed with exit code 1.
```

### Expected behavior

Matrix builds from flags provided

### 'arduino/compile-sketches' version

@v1

### Additional context

I tried to see if it's a string thing with a double yaml.load but it seems fine;

```python
import yaml
cli = yaml.load(wf["jobs"]["compile-sketch"]["steps"][1]["with"]["cli-compile-flags"], Loader=yaml.SafeLoader)
cli
['--build-property build.extra_flags=-VARIANT_SELECTED=${{ matrix.variant }}']
```

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/compile-sketches/issues?q=)
- [X] I verified the problem still occurs when using the latest version
- [X] My report contains all necessary details
