### ISSUE TITLE
Support for latest Mac and Windows OS

### ISSUE THREAD

**Issue by M-ichae-l** [arduino/compile-sketches#253]
### Describe the request

It is possible to let this action runs under 
- windows-latest
- macos-latest

### Describe the current behavior

I have tried the following set up， gives many errors
```
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
```

### 'arduino/compile-sketches' version

main / v1.1.0

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/compile-sketches/issues?q=)
- [X] I verified the feature was still missing when using the latest version
- [X] My request contains all necessary details
