### ISSUE TITLE
Spaces in FQBN are not supported

### ISSUE THREAD

**Issue by micheljung** [arduino/compile-sketches#75]
### Describe the problem

Using an FQBN with spaces, like `"Heltec-esp32:Heltec ESP32 Series Dev-boards:esp32"` fails with `Invalid FQBN: not an FQBN: Heltec-esp32:Heltec`.

Escaping like `"Heltec-esp32:Heltec\\ ESP32\\ Series\\ Dev-boards:esp32"` fails with `Invalid FQBN: not an FQBN: Heltec-esp32:Heltec\`

### To reproduce

```yaml
jobs:
  compile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fqbn:
          - "Heltec-esp32:Heltec ESP32 Series Dev-boards:esp32"
    steps:
      - uses: arduino/compile-sketches@v1
        with:
          fqbn: ${{ matrix.fqbn }}
          platforms: |
            - name: "Heltec ESP32 Series Dev-boards:esp32"
              version: "0.0.6"
              source-url: https://resource.heltec.cn/download/package_heltec_esp32_index.json
```

### Expected behavior

It should not fail.

### 'arduino/compile-sketches' version

v1

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/compile-sketches/issues?q=)
- [X] I verified the problem still occurs when using the latest version
- [X] My report contains all necessary details

**Comment by micheljung** [comment]
Ok I think it works like so:

```yaml
        fqbn:
          - "\"Heltec-esp32:Heltec ESP32 Series Dev-boards:esp32\""
```

**Comment by micheljung** [comment]
Not sure if this is related to spaces or not but it might be:

What to use as fqbn for https://resource.heltec.cn/download/package_heltec_esp32_index.json ? The doc says `VENDOR:ARCHITECTURE` but what corresponds to `VENDOR`?

If I try
```yaml
        fqbn:
          - "\"Heltec-esp32:Heltec ESP32 Series Dev-boards:esp32\""
        with:
          fqbn: ${{ matrix.fqbn }}
          platforms: |
            - name: "Heltec-esp32:esp32"
              version: "0.0.6"
              source-url: https://resource.heltec.cn/download/package_heltec_esp32_index.json
```
I get:
```
  Error during build: Platform 'Heltec-esp32:Heltec ESP32 Series Dev-boards' not found: platform not installed
  Platform Heltec-esp32:Heltec ESP32 Series Dev-boards is not found in any known index
  Maybe you need to add a 3rd party URL?
```

and with
```yaml
        fqbn:
          - "\"Heltec-esp32:Heltec ESP32 Series Dev-boards:esp32\""
        with:
          fqbn: ${{ matrix.fqbn }}
          platforms: |
            - name: "Heltec ESP32 Series Dev-boards:esp32"
              version: "0.0.6"
              source-url: https://resource.heltec.cn/download/package_heltec_esp32_index.json
```
I seem to get a step further:
```
Running command: /home/runner/bin/arduino-cli core install --additional-urls https://resource.heltec.cn/download/package_heltec_esp32_index.json Heltec ESP32 Series Dev-boards:esp32@0.0.6 
[...]
  Invalid argument passed: Found 0 platform for reference "Heltec ESP32 Series Dev-boards:esp32@0.0.6":
```
The command looks like it would need quotes but that seems to be a just display issue; otherwise the error message wouldn't contain the correct string.
